# Introduction to pandas   
- Pandas is a Python library used for data analysis, data cleaning and data manipulation.  
- It helps us work with structured data, especially data in table form, similar Excel sheets, SQL tables, or CSV files.   
- In pandas you can:  
    - Open data
    - Filter the data  
    - Create new columns  
    - Clean missing values  
    - Sort the data  
    - Group the data  
    - Arithmetic operations

In [37]:
# Reading the pandas library  
import pandas as pd

# Main Data Structures in Pandas  
Pandas has 2 main data structures.  
1. Series-This is like a single column  
2. DataFrame-It is like a full table with rows and columns(more than 1 column)  

## Series

In [38]:
students = {'Name':['Benard', 'Kenneth', 'Melody', 'Sharon', 'Juliet']}  

# Create a series  
students_list = pd.Series(students)

print(students_list)

Name    [Benard, Kenneth, Melody, Sharon, Juliet]
dtype: object

## 2. DataFrame

In [39]:
# Example of a DataFrame  
students2 = {'Name':['Benard', 'Kenneth', 'Melody', 'Sharon', 'Juliet'],
             'Course': ['Data Science', 'Data Engineering', 'Software Eng', 'Data Science', 'Data Engineering'],
             'Age': [20, 23, 24, 25, 26]} 



students_info = pd.DataFrame(students2)

# Shift the index to start at 1  
students_info.index += 1

students_info

      Name            Course  Age
1   Benard      Data Science   20
2  Kenneth  Data Engineering   23
3   Melody      Software Eng   24
4   Sharon      Data Science   25
5   Juliet  Data Engineering   26

In [40]:
# DataFrame example 2  
cars = {'Car Brand' : ['Toyota', 'Mazda', 'Peugot', 'Renault', 'Nissan'],
        'Origin': ['Japan', 'Japan', 'France', 'France', 'Japan'],
        'Model' : ['Wish', 'Cx-5', '208', 'Kwid', 'Patrol'],
        'Year' : ['2019', '2015', '2022', '2025', '2024']}  

car_df = pd.DataFrame(cars)
car_df.index += 1

car_df

  Car Brand  Origin   Model  Year
1    Toyota   Japan    Wish  2019
2     Mazda   Japan    Cx-5  2015
3    Peugot  France     208  2022
4   Renault  France    Kwid  2025
5    Nissan   Japan  Patrol  2024

# Reading Data Using Pandas  
__1. CSV file__  
```python  
df = pd.read_csv("mypc/car_df.csv")
```  
__2. Excel file__  
```python  
df = pd.read_excel("mypc/car_df.xlsx") df= pd.read_excel("relative path",sheet_name = "Patients") 
```  
__3. JSON data__  
```python  
df = pd.read_json("mypc/car_df.json",) 
```  
__4. SQL table__  
```python  
from sqlalchemy import create_engine  

engine = create_engine("postgresql+psycopg2://username:password@host:port/dbname")  

df = pd.read_sql("SELECT * FROM cars", con=engine)
```

__Loading Data__

In [41]:
# Housing data  
df = pd.read_csv('nairobi_housing_statistics_dataset.csv')
df

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,1996,Roysambu,Bedsitter,Unfurnished,5,5,88.6,178613.0,5780.0,13.6,...,5.3,94.2,3,Yes,Yes,Expat,Occupied,60.4,165861.0,178613.0
1996,1997,Langata,Apartment,Unfurnished,4,3,81.1,174164.0,5301.0,15.1,...,7.9,92.7,3,No,Yes,Professional,Occupied,67.5,161015.0,174164.0
1997,1998,South C,Townhouse,Furnished,5,6,84.4,205602.0,2309.0,3.5,...,8.0,87.7,3,No,No,Family,Occupied,78.7,178594.0,205602.0
1998,1999,Roysambu,Apartment,Furnished,2,1,78.9,114482.0,4227.0,7.7,...,5.8,88.1,1,No,Yes,Family,Occupied,73.4,99874.0,114482.0
1999,2000,Ruaka,Apartment,Unfurnished,4,4,97.8,256507.0,NaN,21.1,...,9.6,88.8,3,Yes,No,Student,Occupied,79.6,240198.0,256507.0

In [42]:
# Viewing the dataset  
# Displaying the first 5 rows/entries  
print(f"Top 5 entries:\n {display(df.head())}") 

# Displaying the last 5 row/entries  
print(f"Last 5 entries/ rows: \n{display(df.tail())}")

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

Top 5 entries:
 None

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
1995,1996,Roysambu,Bedsitter,Unfurnished,5,5,88.6,178613.0,5780.0,13.6,...,5.3,94.2,3,Yes,Yes,Expat,Occupied,60.4,165861.0,178613.0
1996,1997,Langata,Apartment,Unfurnished,4,3,81.1,174164.0,5301.0,15.1,...,7.9,92.7,3,No,Yes,Professional,Occupied,67.5,161015.0,174164.0
1997,1998,South C,Townhouse,Furnished,5,6,84.4,205602.0,2309.0,3.5,...,8.0,87.7,3,No,No,Family,Occupied,78.7,178594.0,205602.0
1998,1999,Roysambu,Apartment,Furnished,2,1,78.9,114482.0,4227.0,7.7,...,5.8,88.1,1,No,Yes,Family,Occupied,73.4,99874.0,114482.0
1999,2000,Ruaka,Apartment,Unfurnished,4,4,97.8,256507.0,NaN,21.1,...,9.6,88.8,3,Yes,No,Student,Occupied,79.6,240198.0,256507.0

Last 5 entries/ rows:
None

__Checking the shape of your dataset__  
Shape is the number of rows and columns

In [43]:
df.shape

(2000, 21)

__Viewing column names__

In [44]:
df.columns
# converting column to a list
property=df.columns.tolist()
property

['property_id',
 'estate',
 'property_type',
 'furnishing',
 'bedrooms',
 'bathrooms',
 'floor_size_sqm',
 'monthly_rent_kes',
 'service_charge_kes',
 'distance_to_cbd_km',
 'age_of_building_years',
 'security_rating',
 'occupancy_rate',
 'parking_slots',
 'has_backup_generator',
 'has_borehole',
 'tenant_type',
 'vacancy_status',
 'satisfaction_score',
 'rent_2024',
 'rent_2025']

In [45]:
property.remove("rent_2025")
property

['property_id',
 'estate',
 'property_type',
 'furnishing',
 'bedrooms',
 'bathrooms',
 'floor_size_sqm',
 'monthly_rent_kes',
 'service_charge_kes',
 'distance_to_cbd_km',
 'age_of_building_years',
 'security_rating',
 'occupancy_rate',
 'parking_slots',
 'has_backup_generator',
 'has_borehole',
 'tenant_type',
 'vacancy_status',
 'satisfaction_score',
 'rent_2024']

__Viewing general information about the data__

In [46]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   property_id            2000 non-null   int64
 1   estate                 2000 non-null   object
 2   property_type          2000 non-null   object
 3   furnishing             2000 non-null   object
 4   bedrooms               2000 non-null   int64
 5   bathrooms              2000 non-null   int64
 6   floor_size_sqm         2000 non-null   float64
 7   monthly_rent_kes       2000 non-null   float64
 8   service_charge_kes     1970 non-null   float64
 9   distance_to_cbd_km     2000 non-null   float64
 10  age_of_building_years  2000 non-null   float64
 11  security_rating        1970 non-null   float64
 12  occupancy_rate         2000 non-null   float64
 13  parking_slots          2000 non-null   int64
 14  has_backup_generator   2000 non-null   object
 15  has_borehole           2000 non-null   object
 16  tenant_type            2000 non-null   object
 17  vacancy_status         2000 non-null   object
 18  satisfaction_score     1970 non-null   float64
 19  rent_2024              2000 non-null   float64
 20  rent_2025              2000 non-null   float64
dtypes: float64(10), int64(4), object(7)
memory usage: 328.3+ KB

__Summary statistics__  
- Mean - Average  
- Median - Middlemost number/item(categorical)
- Count - NUmber of items  
- Mode - Most appearing

In [47]:
# Numerical summary staatistics  
df.describe().T # you can also trnaspose by adding .transpose()

,count,mean,std,min,25%,50%,75%,max
property_id,2000.0,1000.500000,577.494589,1.0,500.75,1000.5,1500.250,2000.0
bedrooms,2000.0,3.400500,1.446771,1.0,2.00,3.0,4.000,6.0
bathrooms,2000.0,3.407500,1.537734,1.0,2.00,3.0,5.000,6.0
floor_size_sqm,2000.0,84.535700,15.392019,-20.0,74.60,84.6,94.900,131.6
monthly_rent_kes,2000.0,223196.042500,180798.600091,-10000.0,129188.25,190307.5,287698.250,5000000.0
service_charge_kes,1970.0,4991.145178,4250.773577,498.0,2445.00,3881.0,6152.000,81569.0
distance_to_cbd_km,2000.0,10.299500,6.455535,0.4,5.50,8.9,13.600,47.6
age_of_building_years,2000.0,12.040350,5.825776,0.0,7.90,12.0,16.100,33.7
security_rating,1970.0,7.041929,1.208691,2.1,6.20,7.1,7.900,10.0
occupancy_rate,2000.0,89.987400,7.030065,38.0,86.50,91.7,95.300,99.9
parking_slots,2000.0,2.205000,0.924880,0.0,2.00,2.0,3.000,4.0
satisfaction_score,1970.0,75.031269,10.033413,38.8,68.20,75.2,82.175,100.0
rent_2024,2000.0,197121.745000,98598.381747,51867.0,117756.25,173361.0,259789.000,618802.0
rent_2025,2000.0,217312.541500,108001.488354,60067.0,129278.25,189898.5,287015.250,652410.0

In [50]:
# Categorical features 
df.describe(include='object').T

                     count unique           top  freq
estate                2000     15     Westlands   159
property_type         2000      4     Apartment  1092
furnishing            2000      3   Unfurnished  1007
has_backup_generator  2000      2            No  1153
has_borehole          2000      2           Yes  1092
tenant_type           2000      4  Professional   521
vacancy_status        2000      2      Occupied  1670

## Filtering through the data  
### 1. Filtering columns

In [ ]:
df.columns

Index(['property_id', 'estate', 'property_type', 'furnishing', 'bedrooms',
       'bathrooms', 'floor_size_sqm', 'monthly_rent_kes', 'service_charge_kes',
       'distance_to_cbd_km', 'age_of_building_years', 'security_rating',
       'occupancy_rate', 'parking_slots', 'has_backup_generator',
       'has_borehole', 'tenant_type', 'vacancy_status', 'satisfaction_score',
       'rent_2024', 'rent_2025'],
      dtype='str')

In [ ]:
# Selecting one column  
estates_col = df['estate']   

estates_col.head()

0     South B
1       Karen
2       Umoja
3       Ruaka
4    Kasarani
Name: estate, dtype: str

In [ ]:
# Selecting more than one column(multiple columns)  
desired_cols = ['distance_to_cbd_km', 'age_of_building_years', 'security_rating']

stripped_df = df[desired_cols]

stripped_df.head()

   distance_to_cbd_km  age_of_building_years  security_rating
0                 9.9                   21.3              6.5
1                24.5                   17.4              6.9
2                 6.6                   16.5              7.9
3                17.9                   12.9              6.6
4                 3.6                   16.6              6.9

## 2. Selecting rows using loc and iloc
_Using loc_

In [ ]:
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

In [ ]:
# Using the loc method  
df.loc[[30,50,70 ,400]]

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
30,31,Westlands,Apartment,Semi-Furnished,6,6,62.0,323493.0,12308.0,8.1,...,7.4,91.8,4,No,No,Student,Occupied,83.7,293691.0,323493.0
50,51,Roysambu,Bedsitter,Unfurnished,4,5,60.5,106904.0,4440.0,8.5,...,8.4,98.6,2,Yes,Yes,Professional,Occupied,78.9,92619.0,106904.0
70,71,Runda,Apartment,Semi-Furnished,2,2,72.9,408313.0,1385.0,7.6,...,7.4,93.7,2,No,No,Professional,Occupied,70.3,389183.0,408313.0
400,401,Westlands,Bedsitter,Unfurnished,5,5,91.2,531933.0,15337.0,14.2,...,8.1,97.6,4,No,No,Professional,Occupied,74.0,495554.0,531933.0

In [ ]:
# Selecting specific entries using the row index and the column name  
df.loc[30, "furnishing"]

'Semi-Furnished'

_Using iloc_

In [ ]:
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

In [ ]:
# Filtering/Selecting using the row index
df.iloc[[0]]

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0

In [ ]:
# Filtering /Sewlecting using row index and column index  
df.iloc[0]

property_id                         1
estate                        South B
property_type               Apartment
furnishing                Unfurnished
bedrooms                            3
bathrooms                           2
floor_size_sqm                  114.8
monthly_rent_kes             174906.0
service_charge_kes             5549.0
distance_to_cbd_km                9.9
age_of_building_years            21.3
security_rating                   6.5
occupancy_rate                   93.5
parking_slots                       2
has_backup_generator              Yes
has_borehole                       No
tenant_type              Professional
vacancy_status               Occupied
satisfaction_score               71.2
rent_2024                    153825.0
rent_2025                    174906.0
Name: 0, dtype: object

## 3. Filtering using conditional statements e.g greater than, less than, equal to, and, or etc

In [ ]:
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

In [ ]:
# Filtering the units with more than 2 bedrooms  
two_bedroom_plus = df[df["bedrooms"] > 2]

two_bedroom_plus.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0
6,7,Umoja,Apartment,Semi-Furnished,5,4,86.5,102279.0,5675.0,8.9,...,6.9,85.5,3,Yes,Yes,Expat,Occupied,61.6,96234.0,102279.0
7,8,Runda,Apartment,Unfurnished,3,2,55.5,360578.0,8250.0,2.8,...,6.6,95.1,3,Yes,Yes,Student,Occupied,72.5,339209.0,360578.0

In [ ]:
# Filtering the units with less than 2 bedrooms  
two_bedroom_less = df[df["bedrooms"] < 2]

two_bedroom_less.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
31,32,Roysambu,Maisonette,Unfurnished,1,1,66.0,94293.0,2123.0,16.8,...,NaN,97.1,1,No,Yes,Student,Occupied,73.6,80042.0,94293.0
55,56,Runda,Apartment,Unfurnished,1,1,67.7,281499.0,4072.0,19.5,...,6.9,83.2,1,Yes,No,Student,Occupied,62.3,258961.0,281499.0
57,58,South B,Apartment,Semi-Furnished,1,1,74.2,114258.0,4416.0,3.8,...,7.1,85.5,2,No,Yes,Professional,Occupied,90.3,104672.0,114258.0
61,62,Kilimani,Apartment,Semi-Furnished,1,2,84.6,222317.0,5628.0,7.1,...,8.0,95.5,1,Yes,No,Family,Occupied,52.4,201062.0,222317.0

__Multiple conditions__

## handling Nulls
df.isull().sum()

__Thresholds for missing values and handlin g missing values__
_thresholds_
between 0% to 30/40% nulls
more than 30-40% nulls
- fill the nulls using,median(numerical fetures) subjects to the distribution of the datasets.
- for the categorical features/columns fill with the mode.

- more than 40%
  -drop the column,

  - less thhan 5% nulls/missing values
    - fill ,drop the rows

In [ ]:
print(f"{(30/2000)*100}%")

1.5%

In [ ]:
df.isna().sum()

property_id              0
estate                   0
property_type            0
furnishing               0
bedrooms                 0
bathrooms                0
floor_size_sqm           0
monthly_rent_kes         0
service_charge_kes       0
distance_to_cbd_km       0
age_of_building_years    0
security_rating          0
occupancy_rate           0
parking_slots            0
has_backup_generator     0
has_borehole             0
tenant_type              0
vacancy_status           0
satisfaction_score       0
rent_2024                0
rent_2025                0
dtype: int64

    Droping missing values

In [ ]:
#dropping nulls form the whole dataset
# df = df.dropna()
# df.isna().sum()

In [ ]:
#Drop null/missing valus from specific columns
df = df.dropna(subset='service_charge_kes') # for one column
df = df.dropna(subset=['service_charge_kes','column2','column3'])

## Filling nulls

In [ ]:
df.isnull().sum()

property_id               0
estate                    0
property_type             0
furnishing                0
bedrooms                  0
bathrooms                 0
floor_size_sqm            0
monthly_rent_kes          0
service_charge_kes        0
distance_to_cbd_km        0
age_of_building_years     0
security_rating          30
occupancy_rate            0
parking_slots             0
has_backup_generator      0
has_borehole              0
tenant_type               0
vacancy_status            0
satisfaction_score        0
rent_2024                 0
rent_2025                 0
dtype: int64

In [ ]:
# filling nulls/missing values for the satisfaction score
df["satisfaction_score"]= df["satisfaction_score"].fillna(0)

In [ ]:
# filling nulls wit mean
mean_service_charge = df["service_charge_kes"].mean()
print(f"average service charge:{mean_service_charge}")

average service charge:4991.145177664975

In [ ]:
df["service_charge_kes"]=df["service_charge_kes"].fillna(mean_service_charge)

# Dealing with duplicate

In [ ]:
# checking fr duplicates
df.duplicated().sum()

np.int64(0)

In [ ]:
# Assuming there were any duplicates
df = df.drop_duplicates()

_Sorting Data_

sorting is arranging data in a specific order

In [ ]:
#sorting from the smallest totye largerst
df.sort_values("bedrooms",ascending=True)

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
1994,1995,Runda,Apartment,Unfurnished,1,1,90.0,332358.0,8864.0,7.2,...,5.3,97.7,2,No,Yes,Expat,Occupied,84.3,313440.0,332358.0
1993,1994,Donholm,Bedsitter,Unfurnished,1,1,89.4,111916.0,3363.0,5.6,...,5.0,94.4,1,Yes,No,Expat,Occupied,71.3,99549.0,111916.0
1989,1990,Umoja,Apartment,Unfurnished,1,1,95.1,99681.0,2369.0,7.0,...,6.1,94.4,1,No,Yes,Family,Vacant,75.7,88323.0,99681.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
1920,1921,Donholm,Bedsitter,Semi-Furnished,1,1,70.9,68855.0,1695.0,9.2,...,6.0,94.3,1,No,No,Student,Vacant,0.0,66066.0,68855.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
238,239,Kasarani,Maisonette,Unfurnished,6,6,80.4,131080.0,1453.0,3.5,...,6.6,91.5,4,No,Yes,Family,Occupied,73.7,112705.0,131080.0
1479,1480,South B,Maisonette,Unfurnished,6,5,75.3,188625.0,4991.0,13.2,...,7.6,67.8,3,No,Yes,Family,Occupied,69.6,172202.0,188625.0
232,233,Langata,Bedsitter,Unfurnished,6,6,80.1,211559.0,6137.0,20.3,...,7.4,68.4,3,No,Yes,Student,Occupied,59.3,194496.0,211559.0
631,632,Donholm,Maisonette,Semi-Furnished,6,5,112.6,142300.0,2015.0,14.7,...,8.0,95.4,3,No,Yes,Student,Occupied,71.2,131949.0,142300.0
639,640,Kilimani,Apartment,Unfurnished,6,6,69.8,295699.0,2204.0,5.8,...,7.2,78.7,4,No,Yes,Professional,Occupied,61.0,260622.0,295699.0

In [ ]:
# sorting from the desceniding order
df.sort_values("parking_slots",ascending=False)

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
8,9,South B,Maisonette,Semi-Furnished,6,6,81.4,188880.0,2864.0,14.3,...,6.4,84.7,4,No,No,Student,Occupied,63.0,171621.0,188880.0
13,14,Kasarani,Apartment,Furnished,6,6,61.2,127332.0,4177.0,6.4,...,5.1,84.1,4,Yes,No,Family,Occupied,68.6,117803.0,127332.0
1520,1521,Westlands,Maisonette,Semi-Furnished,6,6,108.2,421174.0,3945.0,3.9,...,5.5,97.9,4,Yes,Yes,Family,Vacant,82.8,386220.0,421174.0
723,724,Westlands,Apartment,Unfurnished,6,6,77.0,374161.0,3062.0,4.0,...,8.6,94.5,4,Yes,Yes,Family,Occupied,76.3,330238.0,374161.0
726,727,South B,Maisonette,Semi-Furnished,6,6,99.0,199995.0,6477.0,7.9,...,5.5,92.9,4,No,Yes,Professional,Vacant,48.5,178188.0,199995.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1391,1392,Ruaka,Apartment,Unfurnished,1,2,64.8,137625.0,1064.0,11.8,...,7.1,80.7,0,No,Yes,Student,Occupied,70.9,117733.0,137625.0
1485,1486,Embakasi,Apartment,Semi-Furnished,1,1,77.1,83922.0,4373.0,5.6,...,6.6,85.9,0,No,Yes,Professional,Occupied,57.8,75698.0,83922.0
1581,1582,Embakasi,Bedsitter,Unfurnished,1,1,69.6,94510.0,4503.0,4.5,...,6.5,84.9,0,Yes,Yes,Family,Occupied,66.0,82635.0,94510.0
1536,1537,Ruaka,Apartment,Semi-Furnished,1,1,87.0,162261.0,3729.0,6.6,...,7.0,93.6,0,Yes,Yes,Family,Occupied,92.0,145755.0,162261.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0

# Summarsing Data

## Grouping Data
grouping is used when you categorise data by category
```python
df.groupby(categorical_column)[column you are working]
```
examples of operation you can do are:
- counts .count()
- averages.mean()
- middlemost, median()
- totals .sum()

In [ ]:
# grouping the data by the furnishing ; total of each 
df.groupby("furnishing")["furnishing"].count()

furnishing
Furnished          390
Semi-Furnished     603
Unfurnished       1007
Name: furnishing, dtype: int64

In [ ]:
# grouping the furnishing categories to get the average rent per category
df.groupby("furnishing")["monthly_rent_kes"].median()

furnishing
Furnished         192287.5
Semi-Furnished    184877.0
Unfurnished       192195.0
Name: monthly_rent_kes, dtype: float64

In [ ]:
# average rent per property type
df.groupby("property_type")["monthly_rent_kes"].median()

property_type
Apartment     190281.5
Bedsitter     180285.0
Maisonette    192744.0
Townhouse     198665.0
Name: monthly_rent_kes, dtype: float64

 #  _value counts_

In [ ]:

df["furnishing"].value_counts()

furnishing
Unfurnished       1007
Semi-Furnished     603
Furnished          390
Name: count, dtype: int64

In [ ]:
# count of each estate in the housing dataset
df["estate"].value_counts()

estate
Westlands     159
Kileleshwa    146
Runda         143
Embakasi      142
Roysambu      142
South B       138
South C       135
Donholm       134
Ruaka         130
Umoja         128
Lavington     128
Langata       123
Kilimani      120
Karen         119
Kasarani      113
Name: count, dtype: int64

### working with text data

In [ ]:
# converting columns to lowercase
df["property_type"]=df["property_type"].str.lower()
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

In [ ]:
# converting to uppercase
df["property_type"]=df["property_type"].str.upper()
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,APARTMENT,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,APARTMENT,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,APARTMENT,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,APARTMENT,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,MAISONETTE,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

In [ ]:
df["property_type"]=df["property_type"].str.capitalize()
df.tail()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
1995,1996,Roysambu,Bedsitter,Unfurnished,5,5,88.6,178613.0,5780.000000,13.6,...,5.3,94.2,3,Yes,Yes,Expat,Occupied,60.4,165861.0,178613.0
1996,1997,Langata,Apartment,Unfurnished,4,3,81.1,174164.0,5301.000000,15.1,...,7.9,92.7,3,No,Yes,Professional,Occupied,67.5,161015.0,174164.0
1997,1998,South C,Townhouse,Furnished,5,6,84.4,205602.0,2309.000000,3.5,...,8.0,87.7,3,No,No,Family,Occupied,78.7,178594.0,205602.0
1998,1999,Roysambu,Apartment,Furnished,2,1,78.9,114482.0,4227.000000,7.7,...,5.8,88.1,1,No,Yes,Family,Occupied,73.4,99874.0,114482.0
1999,2000,Ruaka,Apartment,Unfurnished,4,4,97.8,256507.0,4991.145178,21.1,...,9.6,88.8,3,Yes,No,Student,Occupied,79.6,240198.0,256507.0

### Removing spaces

In [ ]:
df["estate"]=df["estate"].str.strip()
df.head()

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
0,1,South B,Apartment,Unfurnished,3,2,114.8,174906.0,5549.0,9.9,...,6.5,93.5,2,Yes,No,Professional,Occupied,71.2,153825.0,174906.0
1,2,Karen,Apartment,Semi-Furnished,5,5,75.2,377170.0,3205.0,24.5,...,6.9,94.0,3,No,Yes,Professional,Occupied,89.4,336858.0,377170.0
2,3,Umoja,Apartment,Furnished,1,1,84.9,84013.0,4526.0,6.6,...,7.9,91.2,0,No,No,Student,Occupied,83.1,71889.0,84013.0
3,4,Ruaka,Apartment,Unfurnished,2,3,75.2,151752.0,2496.0,17.9,...,6.6,98.6,2,No,Yes,Student,Occupied,65.4,137138.0,151752.0
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0

_Checking if text contains_

In [ ]:
# checking if estate column contains Kasarani ,Mombasa
df[df["estate"].str.contains("Kasarani")]

,property_id,estate,property_type,furnishing,bedrooms,bathrooms,floor_size_sqm,monthly_rent_kes,service_charge_kes,distance_to_cbd_km,...,security_rating,occupancy_rate,parking_slots,has_backup_generator,has_borehole,tenant_type,vacancy_status,satisfaction_score,rent_2024,rent_2025
4,5,Kasarani,Maisonette,Unfurnished,3,3,69.6,98368.0,999.0,3.6,...,6.9,94.0,2,No,No,Expat,Occupied,70.8,91765.0,98368.0
12,13,Kasarani,Townhouse,Semi-Furnished,5,4,71.6,138060.0,6783.0,8.9,...,7.7,94.1,3,Yes,No,Family,Occupied,69.4,119228.0,138060.0
13,14,Kasarani,Apartment,Furnished,6,6,61.2,127332.0,4177.0,6.4,...,5.1,84.1,4,Yes,No,Family,Occupied,68.6,117803.0,127332.0
38,39,Kasarani,Maisonette,Semi-Furnished,2,3,102.6,117889.0,7192.0,11.1,...,7.7,95.3,1,Yes,Yes,Student,Occupied,77.4,111920.0,117889.0
39,40,Kasarani,Bedsitter,Unfurnished,3,3,83.8,105489.0,4994.0,4.5,...,7.4,82.4,1,No,Yes,Student,Occupied,91.4,93646.0,105489.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1928,1929,Kasarani,Apartment,Unfurnished,3,4,88.8,100899.0,2937.0,6.3,...,4.6,94.9,2,No,No,Professional,Occupied,80.5,94684.0,100899.0
1938,1939,Kasarani,Maisonette,Semi-Furnished,4,3,78.3,166643.0,7112.0,14.5,...,7.5,84.1,3,Yes,Yes,Expat,Occupied,86.1,149045.0,166643.0
1952,1953,Kasarani,Apartment,Furnished,4,5,78.6,141134.0,3859.0,7.9,...,5.6,96.3,2,No,Yes,Professional,Occupied,83.0,128013.0,141134.0
1979,1980,Kasarani,Apartment,Unfurnished,2,2,71.1,94278.0,5087.0,7.3,...,8.2,92.7,2,Yes,Yes,Expat,Occupied,69.9,80543.0,94278.0
1985,1986,Kasarani,Apartment,Semi-Furnished,2,2,76.1,91051.0,22697.0,1.3,...,8.0,91.7,1,No,No,Student,Occupied,71.2,86903.0,91051.0

## Renaming a column
1. Rename Specific Columns (Recommended)Pass a dictionary to the columns parameter. The keys are your current column names, and the values are your new name

In [ ]:
# Returns a new DataFrame; original remains unchanged
df = df.rename(columns={"old_name": "new_name", "age": "user_age"})

# Working with dates

In [ ]:
import pandas as pd

In [ ]:
data= pd.read_csv('order.csv')
data

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05
5,1006,Faith,2025-03-15,2025-03-20,2025-03-15 12:55:41,2024-11-12
6,1007,George,2025-04-02,2025-04-06,2025-04-02 16:20:05,2024-12-01
7,1008,Hannah,2025-04-20,2025-04-24,2025-04-20 10:40:18,2025-01-15
8,1009,Ian,2025-05-10,2025-05-13,2025-05-10 20:10:55,2025-02-01
9,1010,Jane,2025-05-25,2025-05-29,2025-05-25 11:35:27,2025-03-10
10,1011,Kevin,2025-06-08,2025-06-11,2025-06-08 06:50:44,2025-04-05
11,1012,Lisa,2025-06-22,2025-06-26,2025-06-22 22:15:30,2025-05-01
12,1013,Kim,2025-13-31,2024-18-44,2024-27-98,2928-28-278

In [ ]:
#Converting Date Colums to proper Date Format

dates_columns = ['order_date','delivery_date','last_login','subscription_start']

for column in dates_columns:
    data[column]=pd.to_datetime(data[column],errors='coerce')
data

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start,year of order,year of delivery,year of last_login,yaer of subscription_start
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15,2025.0,2025.0,2025.0,2024.0
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20,2025.0,2025.0,2025.0,2024.0
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01,2025.0,2025.0,2025.0,2024.0
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10,2025.0,2025.0,2025.0,2024.0
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05,2025.0,2025.0,2025.0,2024.0
5,1006,Faith,2025-03-15,2025-03-20,2025-03-15 12:55:41,2024-11-12,2025.0,2025.0,2025.0,2024.0
6,1007,George,2025-04-02,2025-04-06,2025-04-02 16:20:05,2024-12-01,2025.0,2025.0,2025.0,2024.0
7,1008,Hannah,2025-04-20,2025-04-24,2025-04-20 10:40:18,2025-01-15,2025.0,2025.0,2025.0,2025.0
8,1009,Ian,2025-05-10,2025-05-13,2025-05-10 20:10:55,2025-02-01,2025.0,2025.0,2025.0,2025.0
9,1010,Jane,2025-05-25,2025-05-29,2025-05-25 11:35:27,2025-03-10,2025.0,2025.0,2025.0,2025.0
10,1011,Kevin,2025-06-08,2025-06-11,2025-06-08 06:50:44,2025-04-05,2025.0,2025.0,2025.0,2025.0
11,1012,Lisa,2025-06-22,2025-06-26,2025-06-22 22:15:30,2025-05-01,2025.0,2025.0,2025.0,2025.0
12,1013,Kim,NaT,NaT,NaT,NaT,NaN,NaN,NaN,NaN

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            13 non-null     int64
 1   customer_name       13 non-null     object
 2   order_date          12 non-null     datetime64[ns]
 3   delivery_date       12 non-null     datetime64[ns]
 4   last_login          12 non-null     datetime64[ns]
 5   subscription_start  12 non-null     datetime64[ns]
dtypes: datetime64[ns](4), int64(1), object(1)
memory usage: 756.0+ bytes

### Alternative **code** to converting date colums to date format (long process though)

```
data['order_date'] = pd.to_datetime(data['order_date'],errors='coerce')
data['delivery_date'] = pd.to_datetime(data['delivery_date'],errors='coerce')
data['last_login'] = pd.to_datetime(data['last_login'],errors='coerce')
data['subcription_start'] = pd.to_datetime(data['subscription_start'],errors='coerce')
```

### Exrtracting the year,month and day

In [ ]:
# extracting year
data["order_year"]= data["order_date"].dt.year
data["order_month"]= data["order_date"].dt.month_name()
data["order_day"]= data["order_date"].dt.day_name()
data.head()

In [ ]:
order_date = data['order_date']
daliver_date = data['delivery_date']
last_login = data['last_login']
subscription_start = data['subscription_start']

dates_columns = {
'year of order':order_date, 
'year of delivery':daliver_date ,
'year of last_login':last_login ,
'yaer of subscription_start':subscription_start
}

for index,year in dates_columns.items():
    data[index] = year.dt.year.astype('Int64')
data

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start,year of order,year of delivery,year of last_login,yaer of subscription_start
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15,2025,2025,2025,2024
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20,2025,2025,2025,2024
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01,2025,2025,2025,2024
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10,2025,2025,2025,2024
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05,2025,2025,2025,2024
5,1006,Faith,2025-03-15,2025-03-20,2025-03-15 12:55:41,2024-11-12,2025,2025,2025,2024
6,1007,George,2025-04-02,2025-04-06,2025-04-02 16:20:05,2024-12-01,2025,2025,2025,2024
7,1008,Hannah,2025-04-20,2025-04-24,2025-04-20 10:40:18,2025-01-15,2025,2025,2025,2025
8,1009,Ian,2025-05-10,2025-05-13,2025-05-10 20:10:55,2025-02-01,2025,2025,2025,2025
9,1010,Jane,2025-05-25,2025-05-29,2025-05-25 11:35:27,2025-03-10,2025,2025,2025,2025
10,1011,Kevin,2025-06-08,2025-06-11,2025-06-08 06:50:44,2025-04-05,2025,2025,2025,2025
11,1012,Lisa,2025-06-22,2025-06-26,2025-06-22 22:15:30,2025-05-01,2025,2025,2025,2025
12,1013,Kim,NaT,NaT,NaT,NaT,<NA>,<NA>,<NA>,<NA>

In [ ]:
date_columns= [
    'order_date',
    'delivery_date',
    'last_login',
    'subscription_start'
]

for col in date_columns:
    data[f'{col}_month'] = data[col].dt.month
data

In [ ]:
date_cols = [
    'order_date',
    'delivery_date',
    'last_login',
    'subscription_start'
]

for col in date_cols:
    data[f'{col}_day'] = data[col].dt.day_name()
data

In [ ]:
dates_columns = {
'order_quarter':order_date, 
'delivery_quarter':daliver_date ,
'last_login-quarter':last_login ,
'subscription_start_quarter':subscription_start
}

for name,quarter in dates_columns.items():
    data[name] = quarter.dt.quarter.astype('Int64')
data

,order_id,customer_name,order_date,delivery_date,last_login,subscription_start,year of order,year of delivery,year of last_login,yaer of subscription_start,...,last_login_month,subscription_start_month,order_date_day,delivery_date_day,last_login_day,subscription_start_day,order_quarter,delivery_quarter,last_login-quarter,subscription_start_quarter
0,1001,Alice,2025-01-05,2025-01-08,2025-01-05 08:15:22,2024-06-15,2025,2025,2025,2024,...,1.0,6.0,Sunday,Wednesday,Sunday,Saturday,1,1,1,2
1,1002,Bob,2025-01-12,2025-01-15,2025-01-12 14:30:45,2024-07-20,2025,2025,2025,2024,...,1.0,7.0,Sunday,Wednesday,Sunday,Saturday,1,1,1,3
2,1003,Charlie,2025-02-03,2025-02-07,2025-02-03 09:12:10,2024-08-01,2025,2025,2025,2024,...,2.0,8.0,Monday,Friday,Monday,Thursday,1,1,1,3
3,1004,Diana,2025-02-18,2025-02-21,2025-02-18 18:45:33,2024-09-10,2025,2025,2025,2024,...,2.0,9.0,Tuesday,Friday,Tuesday,Tuesday,1,1,1,3
4,1005,Ethan,2025-03-01,2025-03-05,2025-03-01 07:05:12,2024-10-05,2025,2025,2025,2024,...,3.0,10.0,Saturday,Wednesday,Saturday,Saturday,1,1,1,4
5,1006,Faith,2025-03-15,2025-03-20,2025-03-15 12:55:41,2024-11-12,2025,2025,2025,2024,...,3.0,11.0,Saturday,Thursday,Saturday,Tuesday,1,1,1,4
6,1007,George,2025-04-02,2025-04-06,2025-04-02 16:20:05,2024-12-01,2025,2025,2025,2024,...,4.0,12.0,Wednesday,Sunday,Wednesday,Sunday,2,2,2,4
7,1008,Hannah,2025-04-20,2025-04-24,2025-04-20 10:40:18,2025-01-15,2025,2025,2025,2025,...,4.0,1.0,Sunday,Thursday,Sunday,Wednesday,2,2,2,1
8,1009,Ian,2025-05-10,2025-05-13,2025-05-10 20:10:55,2025-02-01,2025,2025,2025,2025,...,5.0,2.0,Saturday,Tuesday,Saturday,Saturday,2,2,2,1
9,1010,Jane,2025-05-25,2025-05-29,2025-05-25 11:35:27,2025-03-10,2025,2025,2025,2025,...,5.0,3.0,Sunday,Thursday,Sunday,Monday,2,2,2,1
10,1011,Kevin,2025-06-08,2025-06-11,2025-06-08 06:50:44,2025-04-05,2025,2025,2025,2025,...,6.0,4.0,Sunday,Wednesday,Sunday,Saturday,2,2,2,2
11,1012,Lisa,2025-06-22,2025-06-26,2025-06-22 22:15:30,2025-05-01,2025,2025,2025,2025,...,6.0,5.0,Sunday,Thursday,Sunday,Thursday,2,2,2,2
12,1013,Kim,NaT,NaT,NaT,NaT,<NA>,<NA>,<NA>,<NA>,...,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>,<NA>,<NA>

## Main Types of errors
- SyntaxError
- RuntimeError
- LogicalErrors(semantic Errors)
### SyntaxError
Syntax errors happen when the code violates the grammatical rules of the Python language
- The Cause: The Python interpreter checks syntax before running the script. If it finds a typo or improper layout, the program will crash immediately without running any code.
- Example: Forgetting a colon at the end of an if statement or leaving a parenthesis unclosed
### RuntimeError
Runtime errors occur while the program is actively executing.
- The Cause: The syntax is perfectly valid, but the computer hits an impossible instruction or operation given the current state of the environment. 
   These are frequently referred to as Python Built-In Exceptions.
   
```
   result = 10 / 0  # ZeroDivisionError: division by zero

```

- **Example**: Forcing -Python to divide by zero (ZeroDivisionError) or using a variable name that hasn't been created yet (NameError).

### LogicalErrors(semantic Errors)
Logical errors mean the program runs entirely from start to finish without generating any official crash messages or exceptions, but it produces the wrong output
- The Cause: The flaw lies strictly in the programmer’s logic, algorithm, or calculations.
-Example: Attempting to calculate the average of two numbers but forgetting to use proper math grouping symbols.

```
# Intending to average 4 and 6. Expected result is 5.
average = 4 + 6 / 2  # Result is 7.0 due to order of operations. 
```

### errors
- errors='coerce' means that any invalid data or parsing errors will be forced into a missing value placeholder instead of crashing your script.
- errors='raise' (Default): Stops execution immediately and throws an error if it finds bad data.
- errors='ignore': Leaves the invalid data exactly as it is and returns the original input unchanged

In [ ]:
# data = data.drop(columns='column')
# data

# Joining two datasets

In [ ]:
# student data

students = pd.DataFrame({
"student_id": [101, 102, 103, 104, 105],
"student_name": ["Brian", "Caren", "Daisy", "Eric", "Faith"],
"course": ["Data Analytics", "Data Engineering", "Data Science", "Data Analytics", "Data Engineering"]
})

# print(f"Stdents data:{display(students)}")

In [52]:
# payments data

payments = pd.DataFrame({
    "student_id": [101, 102, 104, 106, 107],
    "amount_paid": [7500, 15000, 7500, 30000, 10500],
    "payment_status": ["Partial", "Partial", "Partial", "Full", "Partial"]
})

In [53]:
students

   student_id student_name            course
0         101        Brian    Data Analytics
1         102        Caren  Data Engineering
2         103        Daisy      Data Science
3         104         Eric    Data Analytics
4         105        Faith  Data Engineering

In [54]:
payments

   student_id  amount_paid payment_status
0         101         7500        Partial
1         102        15000        Partial
2         104         7500        Partial
3         106        30000           Full
4         107        10500        Partial

Inner Join 
- return only records that exists in both datasets

In [55]:
inner_join_df = pd.merge(payments,students, on = "student_id", how = "inner")
inner_join_df

   student_id  amount_paid payment_status student_name            course
0         101         7500        Partial        Brian    Data Analytics
1         102        15000        Partial        Caren  Data Engineering
2         104         7500        Partial         Eric    Data Analytics

_b).left inner_join_df
- Returns all records from the left side of the datasets
```
inner_join_df = pd.merge(payments,students, on = "student_id", how = "inner")
inner_join_df 
```
- payment datasets is the dataset on thhe left
- students datasets is the dataset to the right

In [56]:
left_join_df = pd.merge(students,payments, on = "student_id", how = "left")
left_join_df

   student_id student_name            course  amount_paid payment_status
0         101        Brian    Data Analytics       7500.0        Partial
1         102        Caren  Data Engineering      15000.0        Partial
2         103        Daisy      Data Science          NaN            NaN
3         104         Eric    Data Analytics       7500.0        Partial
4         105        Faith  Data Engineering          NaN            NaN

In [ ]:
C). Right join 
Returns records

In [57]:
right_join_df = pd.merge(students,payments, on = "student_id", how = "right")
right_join_df

   student_id student_name            course  amount_paid payment_status
0         101        Brian    Data Analytics         7500        Partial
1         102        Caren  Data Engineering        15000        Partial
2         104         Eric    Data Analytics         7500        Partial
3         106          NaN               NaN        30000           Full
4         107          NaN               NaN        10500        Partial

In [68]:
id_student = students["student_id"]
id_payments = students["student_id"]
for id in id_student:
    print(id,end=",")

for id in id_payments:
    print(id,end=",")
    # print(f"payment:{id}")

101,102,103,104,105,101,102,103,104,105,

_d). Full outer join
Returns all recoords from both datasets irregardless if there is a matching record from either dataset

In [69]:
full_outer_df = pd.merge(students,payments, on = "student_id", how = "outer")
full_outer_df

   student_id student_name            course  amount_paid payment_status
0         101        Brian    Data Analytics       7500.0        Partial
1         102        Caren  Data Engineering      15000.0        Partial
2         103        Daisy      Data Science          NaN            NaN
3         104         Eric    Data Analytics       7500.0        Partial
4         105        Faith  Data Engineering          NaN            NaN
5         106          NaN               NaN      30000.0           Full
6         107          NaN               NaN      10500.0        Partial

## Basic Visualization Using Matplotlib and Seaborn